"""add portfolio_snapshots table

Revision ID: efbea2836824
Revises: a56fd7dbdc9d
Create Date: 2026-04-10 20:44:44.628547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbea2836824'
down_revision: Union[str, Sequence[str], None] = 'a56fd7dbdc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_recorded_at'), ['recorded_at'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_app_settings_key'), ['key'])

    with op.batch_alter_table('sentiment_aggregates', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_sentiment_aggregates_ticker'), ['ticker'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentiment_aggregates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_sentiment_aggregates_ticker'), type_='unique')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_app_settings_key'), type_='unique')

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'))

    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
